packages:
  - "packages/*"
  - "docs"
  - "playground"

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - sharp
  - "@tailwindcss/oxide"
  - esbuild
  - better-sqlite3
