export { default as Tabs } from './Tabs.vue'
export { default as TabList } from './TabList.vue'
export { default as Tab } from './Tab.vue'
export { default as TabPanels } from './TabPanels.vue'
export { default as TabPanel } from './TabPanel.vue'
export { TABS_CONTEXT_KEY } from './context'
export type { TabsContextState, TabsContextFactory } from './context'
export type { TabsProps } from './Tabs.vue'
export type { TabListProps } from './TabList.vue'
export type { TabProps } from './Tab.vue'
export type { TabPanelsProps } from './TabPanels.vue'
export type { TabPanelProps } from './TabPanel.vue'
